services:
  # =================== MongoDB Replica Set (3 nodes) ===================
  mongo1:
    image: mongo:7.0
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - mongo1-data:/data/db
    networks:
      - crackhash-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-1
      restart_policy:
        condition: on-failure

  mongo2:
    image: mongo:7.0
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - mongo2-data:/data/db
    networks:
      - crackhash-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-2
      restart_policy:
        condition: on-failure

  mongo3:
    image: mongo:7.0
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - mongo3-data:/data/db
    networks:
      - crackhash-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-3
      restart_policy:
        condition: on-failure

  mongo-init:
    image: mongo:7.0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - crackhash-net
    volumes:
      - ./mongo-init.js:/mongo-init.js:ro
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...';
        sleep 10;
        mongosh --host mongo1:27017 /mongo-init.js;
        echo 'Replica set initiated.';
      "
    restart: "no"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.hostname == node-1

  #  ============================ RabbitMQ =========================
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - crackhash-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-3
      restart_policy:
        condition: on-failure

  #  ============================ Gateway =========================
  gateway:
    image: crackhash/gateway:latest
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo1:27017, mongo2:27017, mongo3:27017
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - crackhash-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node-3

  #  ============================ Worker =========================
  worker:
    image: crackhash/worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - crackhash-net
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

#  ============================ Networks =========================
networks:
  crackhash-net:
    driver: bridge

#  ============================ Volumes =========================
volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
  rabbitmq-data: